### ISSUE TITLE
Min Vid does not stay in foreground

### ISSUE THREAD

**Issue by pdehaan** [meandavejustice/min-vid#1023]
Submitted by @SpeedyGC via https://github.com/mozilla/testpilot/issues/2835:

> **Min Vid Player Problem**
> In the latest update of Min Vid Player, it won't float above other open firefox windows. It can appear, but when I click on other tabs, it goes into the background.

**Comment by SoftVision-CiprianMuresan** [comment]
This is a regression caused by Nightly:
Last good revision: a972e0fb330b7229f86b26dfc75279b44a41c25b
First bad revision: 0ab0630eec0c15b591b379454fe59344bac62290
Pushlog:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=a972e0fb330b7229f86b26dfc75279b44a41c25b&tochange=0ab0630eec0c15b591b379454fe59344bac62290

Seems like [Bug 1394556](https://bugzilla.mozilla.org/show_bug.cgi?id=1394556) introduced this new behavior.

@meandavejustice, is there anything we can do on our side?
I've also opened Bug 1396512.

**Comment by meandavejustice** [comment]
@SoftVision-CiprianMuresan Thanks for tracking down the regression, and opening that bugzilla bug. I'm going to talk to @6a68 and @noitidart and see if they have any ideas

**Comment by 6a68** [comment]
Looks like the problem is the use of `this` as a global in the ostypes code. Should be an easy fix.

-----

More details:

When I launch minvid on my mac, I see this in the browser toolbox console:

<img width="847" alt="screen shot 2017-09-05 at 2 02 45 pm" src="https://user-images.githubusercontent.com/96396/30083355-fd51d8c4-9242-11e7-81e9-819fa93eb1bb.png">

I can get a better traceback if I just try to load the module in the console, then catch and log the error:

<img width="833" alt="screen shot 2017-09-05 at 2 04 02 pm" src="https://user-images.githubusercontent.com/96396/30083393-19a5611c-9243-11e7-8fbd-21c67bee12ac.png">

**Comment by Softvision-MariusComan** [comment]
The issue is no longer reproducible on the latest "Min-Vid" build (0.4.3 from 09/07/2017). I have verified it on on Windows 10 x64, Ubuntu 14.04 and Mac 10.12, with the latest Firefox release (55.0.3) and the latest Nightly (57.0a1).
