### ISSUE TITLE
Figure out how to do two shield buckets

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#1097]
Would be great to have a pref that allows the buckets to be manually set, for QA.

@Osmose can you help us figure this out? Code's in the shield-study branch

**Comment by Osmose** [comment]
The study utils don't handle any of this for you directly, except for the `setVariation` method that ensures Telemetry pings are annotated with the variation you picked. Otherwise, you implement the rest of the branch logic on your own (with some sampling-based helpers).

Here's how the Pioneer enrollment study did it. You should be able to mostly copy this method. It includes the logic for a pref-override.

https://github.com/mozilla/pioneer-enrollment-study/blob/master/extension/bootstrap.js#L240

**Comment by Osmose** [comment]
https://github.com/mozilla/pioneer-enrollment-study/blob/a8703aca37c04d903782cd4bac2d5fd41616e522/extension/bootstrap.js#L240-L265

**Comment by 6a68** [comment]
closing in favor of #1103
