### ISSUE TITLE
A lot of videos are "unembeddable"

### ISSUE THREAD

**Issue by boghison** [meandavejustice/min-vid#1121]
A lot of music videos are marked as "unembeddable", but extensions like "floating for youtube" for Chrome can still display those... Is this by design or a bug?

**Comment by meandavejustice** [comment]
@boghison This is because of the way the extension is implemented, we use the youtube iframe api, where other implementations bypass it. We chose to build it this way temporarily while Min Vid was a Test Pilot experiment and because I'm pretty much working on this alone. First priority when Min Vid gets more resources is to create an implementation which works for all audio and video.
