### ISSUE TITLE
The modal is displayed for a second on install if youtube is already loaded and refreshed

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#1171]
[Affected versions]:
- Firefox Developer Edition 58.0b14
- Firefox Nighlty 59.0a1 (01/08/2018)
- Min-Vid Shield Study Onboarding 0.4.7 (built on 01/10/2018)

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have the "xpinstall.signatures.required" pref set to "false" and "extensions.legacy.enabled" pref set to "true".
- YouTube website is opened.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons" page and select the "Extensions" section.
3. Drag and drop the Min Vid add-on and click the "Add" button.
4. Click the YouTube tab and observe what happens.
BONUS:
5. Refresh the Youtube page.

[Expected result]:
4. The modal is displayed.
5. The modal is no longer displayed.

[Actual result]:
4. Nothing happens, the modal is not displayed.
5. The modal seems to be displayed for ~1 second, then it disappears.

[Notes]:
- Attached a screen recording of the issue:

![modal active and onboarding](https://user-images.githubusercontent.com/26000308/34765454-4003ba50-f5fa-11e7-91f1-606e37e7b296.gif)

**Comment by meandavejustice** [comment]
Okay so this is a weird one, for tabs that are already open you'd think we could use the `onActivated` event. But we don't actually have access to the url so we can't know if it's a youtube tab or not..

The reason it shows up on refresh is because we listen for the `onUpdated` event.

We could only set `seenModal` if when the modal is dismissed. That way the modal will still appear next time a youtube page is opened. And I can dig into a way to not show the modal on this first refresh on a page that was already loaded on install.

**Comment by meandavejustice** [comment]
Updated the title to reflect the new behavior after https://github.com/meandavejustice/min-vid/commit/4ae89cb144f5946e902fe48148dd874dd091fd1c

**Comment by johngruen** [comment]
Add a 500ms delay to the modal
