### ISSUE TITLE
Min Vid locate beyond screen viewpoint.

### ISSUE THREAD

**Issue by BigSully** [meandavejustice/min-vid#1267]
This PIP feature in firefox is absolutely amazing, and it is fluent when displaying video. I am now enjoying it, albeit with some extra work. And I also find some problem which may just happen on my laptop.

1. When I open Min Vid, it is located atop beyond my screen. The cause is  that I have changed my setting of my laptop _Make it easier to read what's on your screen_  to _Medium -125%_, and min-vid doesn't respect it. By the way, I can not drag it down to the viewpoint with my mouse,  and instead I move it down by keyboard. 

1. The Min Vid can still exist with main window of firefox being closed? Namely only the Min Vid window is left.

1. Some video can be played in Min Vid, while others can not, like _https://www.youtube.com/watch?v=Iq3zo432sAU&list=RDEMdN61IXvR_2wuWGTZRHeRLQ_ . I guess the restriction maybe come from youtube site or the author of the video rather than Min Vid.

Image for the first question:
![alt text](https://cdn.makeuseof.com/wp-content/uploads/2012/07/enlarge-text-in-windows.png)

**Comment by SoftVision-CarmenFat** [comment]
Hi @BigSully,

1. If I correctly understand, you say that the Min Vid player opens with its top part hidden so that you can't drag it using the mouse, is that correct?
In this case, can you please tell us if you sent a video or a playlist to the Min Vid player? This might be an already known issue if you're sending a playlist (see issue #842).

2. The Min Vid player should also close once the browser is closed. I've logged this issue here: #1271. 

3. Yes, you are right, some youtube videos are restricted from being embedded by the publisher, there isn't much we can do about this while following the terms of the api besides show an error message.

**Comment by meandavejustice** [comment]
Fixed for shield-study, moving out of milestone. Will apply fix to master and push update to test pilot before end of week.

**Comment by BigSully** [comment]
Hi @SoftVision-CarmenFat , 
1. The top part of the Min Vid player is not hidden, and there is nothing wrong with the window. I mean the setting _Make it easier to read what's on your screen to Medium -125%_ result in the whole player window located out of my windows7 viewpoint.Actually, if i restore the setting of _Make it easier to read what's on your screen_, the player would function well.

1. I made some mistake about my wording here. I mean whether I can keep the player playing but close the main window, namely keeping only the player open?
