### ISSUE TITLE
Can't install Min Vid

### ISSUE THREAD

**Issue by NatoBoram** [meandavejustice/min-vid#1311]
Hello! I just cleaned up my Firefox Developer Edition and now I want to reinstall my Test Pilot extensions. However, the [Min Vid](https://testpilot.firefox.com/experiments/min-vid) experiment is unavailable and I am unable to find up-to-date information on how to installe a signed version of this extension.

I have my old version here, but it'd be better if there was an official way to install it.

[@min-vid.zip](https://github.com/meandavejustice/min-vid/files/1944838/min-vid.zip)

**Comment by meandavejustice** [comment]
Hey @NatoBoram Min Vid is pretty much unsupported at this time, but if you really wanna install your copy, you can install it by switching `extensions.legacy.enabled` to true in `about:config`. Keep in mind that it will stop working soon.

There is a breaking change in 61 (currently in Nightly) https://github.com/meandavejustice/min-vid/issues/1296. Which we may not get around to fixing since, this version of min vid has graduated min-vid.

If you need further help installing, feel free to ping me on irc. JSON_voorhees in the #testpilot channel on mozilla's irc network. :)
