### ISSUE TITLE
The overlay icon is no longer displayed on YouTube videos when you navigate to or return from a video page

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [meandavejustice/min-vid#139]
[Affected versions]:
- Nightly 51.0a1
- Min-vid v0.1.1

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Latest Min-vid add-on version (v0.1.1) was installed on a new profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to YouTube.com page.
2. Hover over recommended videos looking after Min-vid overlay button.
3. Click on one of the videos to open it.
4. Hover over the video looking after Min-vid overlay button.
5. Return or click the "YouTube" top left icon.
6. Hover again over recommended videos looking for Min-vid overlay button.

[Expected result]:
- In all the above cases the Min-vid overlay button is displayed over the video when hovered.

[Actual result]:
- St 2. Overlay is displayed over recommended videos.
- St 4. Overlay is not displayed over the video player.
- St 6. Overlay is no longer displayed over recommended videos.

[Notes]:
- Refreshing the page will display again the overlay in each case.
- If the video is opened in a new tab, the overlay is correctly displayed and clicking on videos from right side recommendations list, will display the overlay for each video. This does not happen if you open a video in the same tab from YouTube home page and after click on recommendations from right side list.
- Added a screen recording with the issue https://goo.gl/eaJHkh .

**Comment by 6a68** [comment]
Jen ran into a similar issue with the vine.co homepage.

It seems like the content script that attaches the overlay icon might be running before the selectors have been inserted into the page. The SDK docs say that content scripts wait for window.onload before running in the page, but a lot of scripts run after page load, in order to improve load time (hence, google ranking).

Using a setTimeout with a few seconds' delay seemed to fix the issue in the case of the vine homepage; I bet it would work here, too.

**Comment by meandavejustice** [comment]
Yeah, there is a simliar issue where lazy loading videos on youtube and other sites won't attach the icons. We will need to check down the road for this and maybe check for new videos on an interval

**Comment by meandavejustice** [comment]
being addressed in #160
