### ISSUE TITLE
The "Click here to move the thing" bar should change its position according to the player's position on the screen

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#195]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.1.6-dev

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Min-Vid add-on version (0.1.6-dev) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites. 
2. Navigate to a website with videos supported by Min-Vid player (eg: YouTube, Vimeo, etc).
3. Send a video to the mini player and choose to play it.
4. Hover the Min-Vid player and observe the "Click here to move the thing" tooltip.

[Expected result]:
- The tooltip and bar appear on top of the video if the player is placed at the bottom of the screen and vice-versa.

[Actual result]:
- The tooltip and bar appear under the video shifting the player position upwards every time when hovered.

[Additional Notes]:
- As an idea, maybe we could restrict the dragging area only to the drag tooltip bar. In this way we can work around some issues that are caused by player dragging.
- Attached a screen recording of the issue http://goo.gl/D8aMoZ.

**Comment by meandavejustice** [comment]
This will be changed into an icon which will be absolutely positioned over the video as a drag handle.

**Comment by SoftVision-CiprianMuresan** [comment]
Good to know, because I've found another interesting issue regarding the drag bar http://goo.gl/b8OL9Z.

**Comment by meandavejustice** [comment]
@SoftVision-CiprianMuresan yeah... that should go away once we get rid of that bar. yikes

**Comment by meandavejustice** [comment]
@6a68 we can track the updates to the drag handle here

**Comment by 6a68** [comment]
@SoftVision-CiprianMuresan Could you file a separate bug for that second video?

> Good to know, because I've found another interesting issue regarding the drag bar http://goo.gl/b8OL9Z.

There are problems initiating drag on linux, but it so far hasn't done anything like that ^^ on windows or mac.

**Comment by 6a68** [comment]
@meandavejustice @johngruen OK, UX question: what if, instead of a drag handle, we show a wide border on hover & switch the pointer to the 'grab' hand to tell users the border is draggable, something like this:

![](https://www.dropbox.com/s/cvtuvl3hn5gyxey/Screen%20Shot%202016-09-06%20at%205.49.35%20PM.png?dl=0&raw=true)

After the user stops dragging and mouses out of the panel, the panel border disappears and the player looks like it usually does:

![](https://www.dropbox.com/s/wjqxbriu6phlvdz/Screen%20Shot%202016-09-06%20at%205.49.30%20PM.png?dl=0&raw=true)

Here's a video of the whole dragging interaction:

https://www.dropbox.com/s/yodmajmgzclaq7k/chrome-border.mov?dl=0

If you want to try it locally, the code is in this branch: https://github.com/6a68/min-vid/tree/WIP-195

**Comment by johngruen** [comment]
@6a68: yeah, I don't hate it. a few nits: 
- [ ] can we make the outer box 24px of padding instead of 30px? 
- [ ] is it possible to add a border radius to a panel. I tried and failed...adding 6px of radius might look nice.
- [ ] could we limit the drag region to the screen dimensions minus whatever padding we add to the drag region?
- [ ] still noticing a bit of drag jank, but this branch looks much better than what's in master

**Comment by SoftVision-CiprianMuresan** [comment]
@6a68 I did as instructed. It should be noted that I haven't been able to reproduce the issue on Mac. #199

**Comment by 6a68** [comment]
@johngruen Thanks very much for the feedback :+1:

>  can we make the outer box 24px of padding instead of 30px?

yup, I can do that

> is it possible to add a border radius to a panel. I tried and failed...adding 6px of radius might look nice.

I'll give it a shot. Maybe `-moz-border-radius`, if this page is still correct: https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Tutorial/Creating_a_Skin

> could we limit the drag region to the screen dimensions minus whatever padding we add to the drag region?

You mean, make it impossible for the panel to scroll off screen? I can look into this, could take 2 seconds or a week--probably better to file a followup bug and add to the MVP milestone. I can file the bug.

**Comment by meandavejustice** [comment]
I would really like to have something better looking for MVP launch. @6a68 Is there any possibility we can just make the whole video draggable like the original mockups from @johngruen?

**Comment by meandavejustice** [comment]
@6a68 I just go this update from @johngruen 

If we can't get the whole video to drag as in the original ui mockups, then we should go with this icon in the control bar as the drag handle.

![](https://irccloud.mozilla.com/file/mH8LXbM9/Screen+Shot+2016-09-07+at+7.57.51+PM.png)

[icon asset](https://www.dropbox.com/s/8a8rr2rlx4rmep8/mover.svg?dl=0)

**Comment by 6a68** [comment]
@meandavejustice Sure, I can give it a try. The problem is that transparent parts of the panel don't seem to trigger dragging--instead, the mouse event fires on whatever's behind the transparent part. This means a transparent drag-detecting overlay probably won't work (dragging the whole vid). Also, I suspect that the drag button in the toolbar would only work if the user moused down on the pixels in the image, not the transparent surrounding area, making it pretty tough to actually start the drag. That said, XUL is full of surprises; I'll mock something up and open a PR to discuss.

**Comment by 6a68** [comment]
Note also that the draggable border could be styled with CSS--setting a color seems to work, at least. The screenshot with the gray outline is using the mac system-level theme color. It could be black instead.

**Comment by 6a68** [comment]
@meandavejustice Looks like the menu button approach does work, with a few quirks. That asset download link seems busted to me, so I used a text 'X' just for the moment.

Here's a vid:
https://www.dropbox.com/s/7lq5vqujfx9ap7o/drag-handle-button.mov?dl=0

Here's the panel on hover:

<img src="https://www.dropbox.com/s/dlua51jj8h052vt/Screen%20Shot%202016-09-08%20at%209.29.24%20AM.png?dl=0&raw=true" width="400">

Here's how the panel looks while dragging--note that the rest of the control bar vanishes. We could  probably use a signal to prevent the controls from disappearing during a drag, though with XUL, adding a drag listener might clobber the XBL drag listeners that make it go.

<img src="https://www.dropbox.com/s/p1v7uwxjfsfav7y/Screen%20Shot%202016-09-08%20at%209.29.29%20AM.png?dl=0&raw=true" width="400">

**Comment by johngruen** [comment]
@6a68 looks good, can you get this svg to work in there: https://www.dropbox.com/s/8a8rr2rlx4rmep8/mover.svg?dl=0

**Comment by johngruen** [comment]
> Here's how the panel looks while dragging--note that the rest of the control bar vanishes. We could probably use a signal to prevent the controls from disappearing during a drag, though with XUL, adding a drag listener might clobber the XBL drag listeners that make it go.

This seems fine

**Comment by meandavejustice** [comment]
@johngruen I also like the current state change.

**Comment by 6a68** [comment]
k, nearly there. just need to get the image sized and scooted into place:

![](https://www.dropbox.com/s/zwc4fcxobu9rud1/Screen%20Shot%202016-09-09%20at%2010.05.01%20AM.png?dl=0&raw=true)

**Comment by johngruen** [comment]
@6a68 looking good, let me know if you need an assist tidying up the UI
