### ISSUE TITLE
[Linux + Nightly] Strange positioning when moving the parent window around

### ISSUE THREAD

**Issue by wresuolc** [meandavejustice/min-vid#329]
STR:

1) Load https://www.youtube.com/watch?v=Yq4KA0mUnC8 and send to min-vid
2) Click on the title bar and move the window around
3) Bonus points: Hold down alt and left-click on the window and move it around (a linux-ism).  This seems to move differently.

The window lags behind the parent window and ends up overlapping or completely outside of the Firefox window.  Occasionally it will pop back into position, like if I click the File menu, or sometimes if I just leave it long enough.  /shrug

Sorry for the imgur, but github upload is erroring on me: http://imgur.com/a/XP9mj

**Comment by 6a68** [comment]
On linux systems, the panel is supposed to be positioned relative to its parent window, using [the built-in XUL `popup.moveToAnchor` method](https://github.com/meandavejustice/min-vid/blob/master/lib/panel-utils.js#L277). This might be a XUL on Linux bug?

The fix is probably to manually force XUL to re-layout the panel. We could check every 10 seconds to see if the window dimensions have changed, and if they have, call the `moveToAnchor` function again. That might interrupt a running video, though.

**Comment by alxpl** [comment]
Being able to move it outside the main window is a nice "feature" for linux users, but having it resume its default position every x seconds would be rather annoying. This actually happens on my system (Fedora 23, firefox-49.0-2, x86_64) when firefox is fullscreen, approximately every 37s.

**Comment by 6a68** [comment]
Should be fixed by #475
