### ISSUE TITLE
Problems with NoScript HTTPS-Only

### ISSUE THREAD

**Issue by rugk** [meandavejustice/min-vid#342]
![minvidnoscriptissue](https://cloud.githubusercontent.com/assets/11966684/18927676/294aa32c-85bd-11e6-9245-57e73d34ef96.png)

NoScript breaks this experiment in my case. I have set it to only allow HTTPS-only.
When I disable NoScript it works again.

**Comment by rugk** [comment]
I discovered that this problem only occurs when you allow all HTTPS scripts by setting the option in "NoScript Options > Advanced > HTTPS > Permissions". When I, however just use the (not-recommend) approach and whitelist "https:", this issue disappears.

**Comment by rugk** [comment]
Also reported to NoScript: https://forums.informaction.com/viewtopic.php?f=10&t=22182

**Comment by rugk** [comment]
It still does not work. Now it displays a loading screen a long time, but finally it also shows the picture I've posted.

**Comment by johngruen** [comment]
@SoftVision-PaulOiegas will look in to this. probably is fixed

**Comment by rugk** [comment]
Yeah, currently I have no problems, but the configuration could have changed too… :smile:

**Comment by SoftVision-PaulOiegas** [comment]
Installed NoScript add-on in today Nightly 56.0a1 and checked the "Allow HTTPS scripts globally on HTTPS documents" option ( from Options > Advanced > HTTPS > Permissions). After doing this, all the supported videos sent to Min Vid were correctly loaded and played. So I think the issue is fixed.
Also tried playing with the other Permission options but the result was still positive.

@rugk just to be sure, you do know that VEVO videos or other protected media (not embeddable) are not supported by Min Vid, right? The message from your screenshot is usually displayed for that kind of media.

**Comment by rugk** [comment]
Yeah, seems to be fixed.
