### ISSUE TITLE
Incorrect length is shown for videos longer than 24h

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [meandavejustice/min-vid#385]
[Affected versions]:
- Firefox 45.0 and up
- Min-Vid 0.3.0-dev

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on version (0.3.0-dev) was previously installed on a clean profile.

[Steps to reproduce]:

1. Open the browser with the profile from prerequisites. 
2. Send [this 24h8s video](https://www.youtube.com/watch?v=7bkk1ibiPRw) or [this 27h7s](https://www.youtube.com/watch?v=WBu2pJpgKEo) to the mini player and observe the video length.

[Expected result]:
- The mini player correctly shows the length of the video.

[Actual result]:
- The mini player shows only the time that's over 24h as the length of the video.

[Additional Notes]:
- Attached a screen recording of the issue https://goo.gl/0xQkGX.

**Comment by pdehaan** [comment]
I'm pretty sure this is due to our use of [`Date#toLocaleTimeString()` in ./components/player-view.js:10-16](https://github.com/meandavejustice/min-vid/blob/e50207e547db09e3fa38bdc575f7637cbdf1e12b/components/player-view.js#L10-L16) which wouldn't be date aware of times longer than 23h 59m.

We'd have to add more checks for dates longer than 1 day so we can do something like 1:03:00:07 (1day, 3 hours, 0 minutes, 7 seconds), or else something like 27:07. Google does the former.

![27_hour_timer_-_youtube](https://cloud.githubusercontent.com/assets/557895/19087098/a46180a0-8a25-11e6-8c1e-27e858c7ade4.png)

But his feels fairly edge case and somewhat lower priority.

**Comment by SoftVision-CiprianMuresan** [comment]
The issue is no longer reproducible on the latest build (0.3.1).
