### ISSUE TITLE
Investigate Object / Method Combos

### ISSUE THREAD

**Issue by rayborn** [meandavejustice/min-vid#390]
With order of 100k pings, I'm not seeing all the listed object/method combos (see [this Re:dash chart](https://sql.telemetry.mozilla.org/queries/1321#2314))

I haven't seen the following metrics.md states:
- contextmenu/activate - _this should be the a somewhat common state_
- error_view/render
- loading_view/render
- player_view/render
- overlay_icon/available - _this should be the most common state_

**Comment by meandavejustice** [comment]
@rayborn I will look into this asap. I should have an answer for you today/tomorrow morning.

**Comment by meandavejustice** [comment]
Okay @rayborn I'm about to open a pull request with fixes for both`contextmenu/activate` and `overlay_icon/available`. I had removed the `render` metric from loading, error, and player views, because I felt they were possibly excessive(although I had forgotten to update `docs/metrics.md`) I still think `player_view` and `loading_view` `render` events would be excessive. But I am added back in `render` for `error_view` since it can be used to reliably show us # of errors for the time being.

What do you think?

**Comment by rayborn** [comment]
@meandavejustice - Right now I haven't been asked to do anything with the "render" method; I was just commenting about the diff from metrics.md for completion.  "Available" and "activate" will by hugely helpful, and we'll probably use some "error_view" at some point.

Thanks for the work and updates.

**Comment by meandavejustice** [comment]
@rayborn Great, this code will land in #400, but I'm going to leave this issue open until we ship and update and these events start showing up for you.

**Comment by meandavejustice** [comment]
@rayborn The update was shipped on friday. You should start seeing pings soon.
