### ISSUE TITLE
Min-Vid icon and "Send to mini player" option are missing if the browser is in Private Window mode

### ISSUE THREAD

**Issue by meleephd** [meandavejustice/min-vid#431]

**Comment by meandavejustice** [comment]
@meleephd Can you provide some context to what you were right clicking? We currently only support YouTube and Vimeo, though html5 video support is planned

**Comment by meleephd** [comment]
Yes, to test it I went to YouTube and tried right-clicking on various
titles.  Looking in the add-ons and in about:config, I see Min-vid is
installed and enabled, but have no idea how to activate it without any menu
icon or context menu items.  Thanks for the reply.

**Comment by vickychijwani** [comment]
I'm seeing something similar: I don't see the "Send to mini-player" option when right-clicking any thumbnail on YouTube (homepage, search results, you name it). But I do see the icon, as well as the context menu option, on right-clicking the video title text.

**Comment by meleephd** [comment]
I con't get anything no ion, no contest menu item, no regular  menu item, nothing.

**Comment by Softvision-VladBacia** [comment]
Hello @meleephd . Can you give me a little more info regarding this issue?

-Operating system
-Firefox version
-Link to video link (if u feel comfortable sharing)
-Any further steps to reproduce. From where did you installed the add-on? Did you use normal browsing mode or private window. 
Any information provided is useful in finding the root cause of the problem.

**Comment by meleephd** [comment]
OS = Windows 7
Firefox = 49.0.1
installed Min-vid via Firefox "Rest Pilot" in private window mode
Any video link, tests at Youtube clicking on video titles (not thumbnails)

**Comment by meleephd** [comment]
Install using Firefox "Test Pilot"

**Comment by Softvision-VladBacia** [comment]
@meleephd , from what I know, Min-Vid experiment doesn't work in Private Window browsing.

**Comment by meleephd** [comment]
One would think that should be posted in the add-on description so one would know this before installing.  Thanks for the reply.

**Comment by ettoolong** [comment]
You need add "private-browsing" permission in package.json to support private browsing mode.

For this case example:
"permissions":{
    "multiprocess": true,
    "private-browsing": true
}

**Comment by ldgbc** [comment]
Thank you. Here is a more in depth of how to do this manually (until it get update or the team add the code onto it).

Open: about:profiles
Open your current profile. Go to \extensions
Extract package.json from @min-vid.xpi (use 7z or similar software)
Use text editor (e.g. notepad++)
Find and copy/paste the example ettoolong said.
Make an copy of @min-vid.xpi
Overwrite package.json on the new @min-vid(copy).xpi
Open Add-on Manager (Ctrl+Shift+A)
Drag and drop the  @min-vid(copy).xpi into the add-on managers
Install

**Comment by 6a68** [comment]
Private browsing mode puts restrictions on what data websites can read or write. The minvid window can't provide those guarantees, so I think it probably is best to not support private browsing. @meandavejustice any thoughts?

**Comment by joanbm** [comment]
Meanwhile, if this extension can't work in private browsing mode, I think that adding some kind of warning to the user is warranted. I also use permanent private browsing mode and it took me a while to figure out that it was this setting that was causing the problem. I imagine that since Test Pilot is sometimes promoted on the Firefox startup page, this isn't too uncommon.

@6a68 Is safely supporting private browsing mode technically impossible, or just requires some extra dev. work?

While I'll be probably too busy at the end of the day, I would love to put some dev. work if this can be made to support private browsing, or even just a UI hint as I commented above. I really enjoy this add-on, but I hate that I have to install Firefox Dev + unsigned add-ons + assume (small?) privacy risk for it to work with my setup.

**Comment by SoftVision-CiprianMuresan** [comment]
Min Vid options now also appear if the browser is in private mode.
