### ISSUE TITLE
add support for soundcloud playback

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#445]
depends on #443 
- [ ] context-menu support for embeds
- [X] context-menu support for direct links
- [X] overlay icon support for embeds
- [X] create `lib/get-soundcloud-url.js` for resolving the stream [soundcloud-resolve](https://github.com/hughsk/soundcloud-resolve)

**Comment by SoftVision-PaulOiegas** [comment]
Overlay icon is indeed displayed on SoundCloud embeds, but only if you navigate on the song page. Would it be implemented also on the suggestions like on YouTube & Vimeo ?

**Comment by meandavejustice** [comment]
@SoftVision-PaulOiegas it should also be on the `/stream` page. I will go through today and make a list of all the places it may be useful so we can have wide support

**Comment by SoftVision-PaulOiegas** [comment]
@meandavejustice Have you got a chance to make that list ? 
Also, do we want to have that overlay icon in more places before launch or we will add more support in the next release ? Since we have a wider support on YouTube and Vimeo, maybe we should consider to add it in more places for this release.
