### ISSUE TITLE
Audio Support UI

### ISSUE THREAD

**Issue by meandavejustice** [meandavejustice/min-vid#448]
meta issue to discuss possible uis for launching audio into min vid

**Comment by clouserw** [comment]
When Firefox has a tab playing sound, we show a little sound icon on the favicon, but I still have to dig through my tabs to find it.  

What if, for audio only (not videos), we just recognized that a page was playing audio and *automatically* put it in min vid.  Then I'd have a consistent place to interact with audio coming out of my browser.  I'm imagining:

1) Load a page with an <audio> element
2) Click the Play button.  There is some kind of friendly animation showing the min vid UI appearing so I notice it, but it doesn't remove the existing UI.  I can interact with this audio element from min vid or the original page UI
3) I switch tabs, but min vid stays on top, like usual

If the <audio> is autostart, we can just do the animation with the page load.  

What happens when two pages try to play audio?  I have no idea!

**Comment by wresuolc** [comment]
We're dropping support for soundcloud and vimeo
