### ISSUE TITLE
Min Vid Unapparent

### ISSUE THREAD

**Issue by eisceire** [meandavejustice/min-vid#454]
Initially min-vid worked as said out of box. Now whenever I click on it in a YT window my computer acts as if min-vid is not there. That is it gives me the standard YT drop-down controls and min-vid does not activate.

My specs are Win 10 / 64 on Firefox 49.1. I haven't tested this on other browsers. I have cleared cache and deactivated/reactivated min-vid. These steps haven't solved the issue.

**Comment by Softvision-VladBacia** [comment]
@eisceire thank you for reporting this issue.
From the description I can understand that the issue is on Win 10 x64 with Firefox latest release 49.0.1. I've tried to reproduce this issue on the same system but I could not.

Please, can you provide more information regarding:
-User Agent for Firefox from about:support page
-Link to video link (if u feel comfortable sharing)
-Any further steps to reproduce. Did you use normal browsing mode or private window?
- Screenshot/video of the issue.

**Comment by meandavejustice** [comment]
Closing as this is over 2 months old with no response, @eisceire feel free to reopen if you are still having the issue.
