### ISSUE TITLE
Remove vine code(REVERT)

### ISSUE THREAD

**Issue by 6a68** [meandavejustice/min-vid#473]
Looks like vine is riding off into the sunset: https://medium.com/@vine/important-news-about-vine-909c5f4ae7a7#.kvzwxbs1e

We should rip out any vine-related code as time allows.

**Comment by Fiaxhs** [comment]
But the videos will stay online for now, so this could be useful.

> Once you shut down will I still be able to post or just watch?
> 
> Our plan is that Vines will be available to watch on the vine.co website, Twitter, and anywhere else you shared your Vines over the years.

**Comment by meandavejustice** [comment]
@Fiaxhs True. I'd really like to not have to maintain our overlay icons in the case of vine embeds since hardly anyone seems to use min-vid with vines. We may see more interest in them once we add the play queue/playlists, as you'll be able to watch hashtags of vines instead of the same one over and over.

I'd be open to reverting this commit to allow launching context-menu, what do you think @6a68

**Comment by meandavejustice** [comment]
closed in https://github.com/meandavejustice/min-vid/commit/8e0146c553bbedd86450af30301cc9032b3d70ca
