### ISSUE TITLE
Looping videos

### ISSUE THREAD

**Issue by ayunami2000** [meandavejustice/min-vid#621]
When I right clicked and hit loop, when at the end, you have to pause and unpause the video to get the replay menu to go away. Also, please add an option to resize the window, and a dropdown for more options, such as loop, quality, captions and speed.

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @ayunami2000, 
Thank you for reporting this, I can confirm that the issue is reproducible on all OS'es.

However, regarding the other issues that you have described:
- "an option to resize the window" is already tracked in #69.
- "a dropdown for more options", could you log a separate issue for this?
- Captions are displayed in the mini player if the video you sent to it already had captions enabled.
