### ISSUE TITLE
yt music videos aren't displayed

### ISSUE THREAD

**Issue by user54lrolhrok** [meandavejustice/min-vid#785]
I experience that most youtube music videos (p.e. of vevo) can't be displayed and mini vid shows the typical grey-white pixel picture. The problem isn't neighter related to addons nor to the Firefox version (tried 49, 50, 51, 52, 53). I tried mini vids serveral times over the last months and ALWAYS had this problem.
 I love the idea of this addon but this problem makes it useless to me because appr. 95% of all music videos can't be played :( . 

Example: https://www.youtube.com/watch?v=CevxZvSJLk8

![unbenannt](https://cloud.githubusercontent.com/assets/28097451/25482102/7d09c6bc-2b50-11e7-86f1-ee308f37ebc0.png)
![unbenannt2](https://cloud.githubusercontent.com/assets/28097451/25482101/7d04fd76-2b50-11e7-98a2-c46996c90971.png)

Firefox 53.0 x64, Windows 7, 8GB RAM

**Comment by user54lrolhrok** [comment]
Is this problem related to #362 ?

**Comment by SoftVision-PaulOiegas** [comment]
As far as I know this is caused by the option that most of the major video channels use. That of not allowing the videos they post to be embedded. Sending a video to Min Vid player is much like embedding it in a page. So I don't think there's a workaround for now because of legal reasons (#683).  It's not that the developers don't want to offer full support...

I hated this too, a lot. But then I thought, hey, this is a mini player, if I want to watch a video, I almost always do it in full screen. This is not the purpose of the mini player. So, as a workaround, I did a playlist of just the audio version of the songs that I like. Those are working perfect, and now I enjoy my music from Min Vid.

I'm not saying you should do the same, but for the moment, I don't know a better solution.

**Comment by meandavejustice** [comment]
@SoftVision-PaulOiegas Did a good job explaining the situation. We have no control over what VEVO restriction settings.
