### ISSUE TITLE
YouTube video playback stutters if the user chooses to "Replay" it

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [meandavejustice/min-vid#836]
**[Notes]:**
- This issue is related to #626 where the behavior was partially fixed.

**[Affected versions]:**
- Firefox v53.0.2 and up
- Min-Vid v0.3.6 (custom repo build)

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Latest Min-Vid add-on was previously installed on a clean profile from custom repo build.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to https://youtube.com.com page.
2. Hover a suggested video and click the overlay "Play Now" button.
3. Fast forward the video almost at the end in order to have the "Replay / Close" overlay displayed.
4. After the overlay is displayed, click the "Replay" button.
5. Observe the player behavior.

**[Expected result]:**
- The video is correctly replayed with no playback issues.

**[Actual result]:**
- The video is replayed, but the playback is randomly stuttering and the "Play / Pause" button is constantly switching states.

**[Additional notes]:**
- The issue is always occurring on Windows and Linux, but randomly on Mac OS. 
- Here is a screen recording of the issue: https://goo.gl/EqckTk.

**Comment by meandavejustice** [comment]
I've put a lot of hours into this issue so far and still haven't come up with a solid solution for this. After running git bisect I narrowed it down to this commit https://github.com/meandavejustice/min-vid/commit/bed7db6ea9fe7226105dfa3406470aa4533cada8

If change functionality in `onEnded` to _not_ set `playing` to false, the stuttering goes away. I think I'm going to do that for now and reopen #788. This is really weird behavior as it only happens with YouTube embeds, which leads me to believe there may be an underlying issue with react-player. The issue is hard to describe so I'm going to have to try to reproduce it in a testcase in jsfiddle and try and get to the bottom of it with the author of react-player.

**Comment by SoftVision-PaulOiegas** [comment]
The issue no longer occurs on today (05/12/2017) custom repo build. 👍

**Comment by SoftVision-CarmenFat** [comment]
Reopening this issue since it's reproducible again on the latest Min Vid v.0.4.3 (custom repo build on 12/09/2017) across platforms.

**Comment by SoftVision-CarmenFat** [comment]
This issue is no longer reproducible using today's custom repo build (9/22/2017).
