### ISSUE TITLE
"Remove" button is not displayed when hovering an item from Play queue

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [meandavejustice/min-vid#942]
[Affected versions]:
- Firefox 54.0.1 and up
- Min-Vid 1.0.10

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Min-Vid add-on (1.0.10) was previously installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to one of the supported platforms (e.g www.youtube.com).
2. Send a video to the Min Vid player with the Play Now option.
3. Click the "Open Queue" button.
4. Hover the video from Play Queue and observe what happens next.

[Expected result]:
- "X" (remove) button is displayed on the right side of the item.

[Actual result]:
- "X" (remove) button is not displayed on the right side of the item.

[Notes]:
- Attached a screen cast of the issue:

![remove button](https://user-images.githubusercontent.com/26000308/28915074-a207914a-7846-11e7-920a-13310422eeeb.gif)

**Comment by meandavejustice** [comment]
In the screenshot it looks like you are using a really thin width which is why they are not showing up. We discussed this in a previous bug and decided to have stricter dimensions, which could still use some work. I'm going to close this since we have other bugs logged dealing with the allowed dimensions, and this behavior shouldn't be seen by default

**Comment by Softvision-VladBacia** [comment]
We are using this resolution because there is no way to change it. For now this is an issue because we cannot test the remove functionality and we do not know if it works as expected. Test are failing because of this. 
Reopening this issue until we have the possibility to test the remove functionality.

**Comment by meandavejustice** [comment]
Possibly fixed in https://github.com/meandavejustice/min-vid/commit/a5011ab2071492f98a4d1a0e9b2546c0be33e4cf

**Comment by meandavejustice** [comment]
@Softvision-VladBacia Can you take another look at this one now that the resolution bugs should be fixed? So long as the remove button is visible at the default dimensions I feel comfortable closing this. I feel we can't be responsible for each and every resolution. only what we deem reasonable

**Comment by Softvision-VladBacia** [comment]
@meandavejustice I agree with the fact that we can't adjust everything to every resolution, , but let's do as much as we can :relaxed: .

In the build received from you the "Remove" button it is displayed when using default resolution. Thus, we can close this issue as Verified-Fixed.
