### ISSUE TITLE
Stop work on Firefox Develper Edition 56.0b1 >   (64-bit)

### ISSUE THREAD

**Issue by Westfallx** [meandavejustice/min-vid#978]
The Min Vid menu not appear in the video window, allowing one to switch playback over to using Min Vid or add the video to the Min Vid queue.

Windows 10 and ubuntu 14.04

Installed  test pilot

Firefox Develper Edition 56.0b1,  56.0b2

**Comment by SoftVision-CiprianMuresan** [comment]
Hi @Westfallx, thanks for the report. However, on Beta due to a sandboxing issue (that is fixed in Nightly) multiple components are not working properly. A workaround for this issue is to set the "security.sandbox.content.level" pref from about:config to 0 (from 3) and restart the browser. A future browser update will fix this issue.

**Comment by Westfallx** [comment]
@SoftVision-CiprianMuresan Thx for help.. its work :D
